# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo apt install -y unixodbc-dev wget alien
        sudo wget https://download.dremio.com/odbc-driver/dremio-odbc-LATEST.x86_64.rpm
        sudo alien dremio-odbc-LATEST.x86_64.rpm
        sudo dpkg -i dremio-odbc*.deb
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt
    - name: Test with pytest
      env:
        DREMIO_CONNECTION_URL: ${{ secrets.DREMIO_CONNECTION_URL }}
      run: |
        pytest
    - name: Publish to PYPI
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      run: |
        python setup.py sdist
        twine upload -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }} dist/*
